### PR TITLE
hidpp20: add ADC measurement (0x1f20) feature

### PR DESCRIPTION
**Pull request by kdomanski**
Signed-off-by: Kamil Domański <kamil@domanski.co>

### CODE REVIEW

**Comment by FFY00** [comment]
For this to go in it needs to be rewritten in restructuredtext.

See https://github.com/Logitech/cpg-docs/blob/master/hidpp20/features/0x0000-IRoot.rst for the format.

**Comment by xnlcasad** [comment]
Thanks Kamil, for the contribution, as @FFY00 said it would be much appreciated if this can be rewritten in .rst.

**Comment by kdomanski** [comment]
Updated.

**Review by FFY00 — CHANGES_REQUESTED** [review]
We want to have a standard format, so please follow the format at https://github.com/Logitech/cpg-docs/blob/master/hidpp20/features/0x0000-IRoot.rst. Just converting the document to rst is not enough for this repo. If you don't want to do it, I will do it later, no worries :)

**Pull request closed without merging**
